Np 1384 include username
BIBSYSDEV/nva-doi-requests-api pull request #22
Opened 2020-08-31 19:14 UTC by axthosarouris

2020-08-31 19:18 UTC, axthosarouris commented on build.gradle
> +        jacksonVersion = '2.10.2'
we cannot define global variables but we can define extra properties for libraries that are used in multiple projects

2020-08-31 19:25 UTC, axthosarouris commented on doi-requests-commons/src/main/java/no/unit/nva/doi/requests/service/impl/DynamoDBDoiRequestsService.java
> -    private DoiRequestMessage createMessage(CreateDoiRequest createDoiRequest) {
moved lower

2020-08-31 19:26 UTC, axthosarouris commented on create-doi-request/src/main/java/no/unit/nva/doi/requests/handlers/CreateDoiRequestHandler.java
> +        String username = UserDetails.getUsername(requestInfo);
This is where the handler supplies the username to the service.

2020-08-31 19:30 UTC, axthosarouris commented on doi-requests-commons/src/main/java/no/unit/nva/doi/requests/service/impl/DynamoDBDoiRequestsService.java
> +    private void validateUsername(Publication publication, String username) throws ForbiddenException {
new method for implementing the check on the username

2020-08-31 19:33 UTC, axthosarouris commented on doi-requests-commons/src/main/java/no/unit/nva/doi/requests/userdetails/UserDetails.java
> +    public static final String ROLE = "role";
Functionality taken out from `FindDoiRequestHandler` to re-use in `CreateRequestHandler`.

2020-08-31 19:35 UTC, axthosarouris commented on doi-requests-commons/src/test/java/no/unit/nva/doi/requests/userdetails/UserDetailsTest.java
> +    public void init() throws JsonProcessingException {
Tests for code coverage. Bad case scenarios were not implemented as the  methods perform only a library call.

2020-08-31 19:36 UTC, axthosarouris commented on doi-requests-commons/src/test/resources/requestInfoWithContext.json
> +  "requestContext": {
expected format of the user-info in the requestContext

2020-08-31 19:36 UTC, axthosarouris commented on find-doi-requests/src/main/java/no/unit/nva/doi/requests/FindDoiRequestsHandler.java
> +            user = UserDetails.getUsername(requestInfo);
Code replaced by the common `UserDetails` class

2020-08-31 19:57 UTC, brinxmat requested changes

2020-08-31 19:57 UTC, brinxmat commented on build.gradle
> +        testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: project.ext.get("junit5Version")
can you not use the project.junit5Version syntax?

2020-08-31 19:57 UTC, brinxmat commented on build.gradle
> +    ext{
project.ext, I think

2020-08-31 19:57 UTC, brinxmat commented on create-doi-request/src/test/java/no/unit/nva/doi/requests/handlers/CreateDoiRequestHandlerTest.java
> +    private void assertThatProblemDetailsDoesRevealSensitiveInformation(Problem details,
Nice!

2020-08-31 19:57 UTC, brinxmat commented on create-doi-request/src/test/java/no/unit/nva/doi/requests/handlers/CreateDoiRequestHandlerTest.java
> +            .putObject("authorizer")
These can be constants

2020-08-31 19:57 UTC, brinxmat commented on doi-request-common-constants/build.gradle
> +    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: project.ext.get("jacksonVersion")
Use dot syntax

2020-08-31 19:57 UTC, brinxmat commented on doi-requests-commons/build.gradle
> +    api group: 'com.github.BIBSYSDEV', name: 'nva-commons', version: project.ext.get("nvaCommonsVersion")
Use dot syntax

2020-08-31 19:57 UTC, brinxmat commented on test-module/build.gradle
> +    implementation group: 'com.github.BIBSYSDEV', name: 'nva-datamodel-java', version: project.ext.get("nvaDatamodelJavaVersion")
Dot syntax

2020-09-01 07:57 UTC, brinxmat approved these changes

2020-09-01 07:57 UTC, brinxmat commented on build.gradle
> +        nvaCommonsVersion = '0.4.4'
Consider also bumping aws, junit, mockito to latest, or setting up Dependabot

2020-09-01 08:14 UTC, merged