NP-1500: update nva-commons
BIBSYSDEV/nva-doi-requests-api pull request #30
Opened 2020-09-18 12:43 UTC by axthosarouris

2020-09-18 12:43 UTC, axthosarouris commented on find-doi-requests/src/main/java/no/unit/nva/doi/requests/FindDoiRequestsHandler.java
> +    @Override
moved from line 112, due to auto-formatting

2020-09-18 14:03 UTC, brinxmat approved these changes

2020-09-21 06:43 UTC, norrs commented
I've already done this in https://github.com/BIBSYSDEV/nva-doi-requests-api/pull/28 FYI, rather get this PR merged but @brinxmat left some feedback on friday afternoon that I fixed now this morning.

2020-09-21 06:43 UTC, norrs commented
FYI @axthosarouris

2020-09-22 06:47 UTC, norrs requested changes
We dont need this PR, but if you want to run a auto-reformat on the whole class, go a head and run it and push and update and rename title on PR.

2020-09-22 06:56 UTC, closed without merging