Np 1804 handle access denied errors
BIBSYSDEV/nva-doi-requests-api pull request #48
Opened 2020-11-13 08:32 UTC by axthosarouris

2020-11-13 13:42 UTC, axthosarouris commented on doi-requests-commons/src/main/java/no/unit/nva/doi/requests/service/impl/DynamoDBDoiRequestsService.java
> +    public DynamoDBDoiRequestsService(Table table, Index index) {
to use in testing

2020-11-13 14:04 UTC, brinxmat requested changes

2020-11-13 14:04 UTC, brinxmat commented on doi-requests-commons/src/main/java/no/unit/nva/doi/requests/service/impl/DynamoDBDoiRequestsService.java
> +        if (exception instanceof AmazonDynamoDBException) {
Extract to e.g. 
```
    private boolean isAccessDeniedException(Exception exception) {
        return exception instanceof AmazonDynamoDBException 
                && exception.getMessage().contains(ACCESS_DENIED_ERROR_MESSAGE);
    }
```

2020-11-13 14:13 UTC, brinxmat approved these changes

2020-11-14 00:57 UTC, norrs approved these changes

2020-11-16 07:43 UTC, janbj approved these changes

2020-11-16 08:04 UTC, merged